// Note: application state is generated by reducers
export default function() {
  return [
    {
        id: 1,
        title: 'React',
    },
    {
        id: 2,
        title: 'CSS',
    },
    {
        id: 3,
        title: 'DevOps',
    },
    {
        id: 4,
        title: 'Node.js',
    },
    {
        id: 5,
        title: 'Databases',
    }
  ];
}